### ISSUE TITLE
How to output the evaluation result

### ISSUE THREAD

**Issue by AmingWu** [henryhungle/MTN#1]
Hello, I run your code. But I do not know how to output the evaluation result, i.e., B1, B4, Meteor, and CIDer.
![QQ截图20190724122127](https://user-images.githubusercontent.com/38445175/61765023-e0c00800-ae0d-11e9-8acc-6405fb0fad0c.jpg)

**Comment by henryhungle** [comment]
Could you check the .eval file in the output experiment folder? The file contains execution log of the evaluation code

**Comment by Cathy-t** [comment]
Sorry to open the closed issue.I run the code ,and solved some problems.
But after the Java environment was installed,the execution log of the evaluation code shown some usages like that：
![image](https://user-images.githubusercontent.com/39083599/76207835-7a231980-6239-11ea-850e-07081586b5f3.png)
I don't know why.Could you help me ?
