### ISSUE TITLE
Cannot seem to find 'data/stopwords.txt'.

### ISSUE THREAD

**Issue by xubuvd** [henryhungle/MTN#10]
missing file 'data/stopwords.txt' when running 'stage 4: score results'.

**Comment by henryhungle** [comment]
Thanks, @xubuvd. To evaluate with stop words, you can use the attached file. 
You can refer to #5  for the results with stop words and multi-reference ground truth.
[stopwords.txt](https://github.com/henryhungle/MTN/files/5097890/stopwords.txt)
