### ISSUE TITLE
How can I download file 'visual_features_resnet15_all_py2.pk'?

### ISSUE THREAD

**Issue by StarrySkyLYX** [henryhungle/MTN#12]
When I run the run.sh, I could not find the feature file 'visual_features_resnet15_all_py2.pk'. Could you please tell me how can I obtain this file? Thank you!

**Comment by satwikkottur** [comment]
Hello @StarrySkyLYX ,

Thanks for your interest. For the time being, I've hosted the `visual_features_resnet15_all_py2.pk` file [here][1]. Will update the repository soon.

[1]:https://drive.google.com/drive/folders/1qcKZD4h_KhxbYimzX7X7dBCT0reEPuaM?usp=sharing

**Comment by StarrySkyLYX** [comment]
Thanks for your help!
