### ISSUE TITLE
How to generate the lbl*.json file under data/ folder

### ISSUE THREAD

**Issue by BigFishMaster** [henryhungle/MTN#2]
How to generate the following files under data/ folder? It is different from the officical files under ```dstc7avsd_eval``` folder(e.g., ```test_set4DSTC7-AVSD_multiref.json```).
```
lbl_test_set4DSTC7-AVSD.json
lbl_undiscloseonly_test_set4DSTC7-AVSD.json
```

**Comment by BigFishMaster** [comment]
The groud truth in ```lbl_undiscloseonly_test_set4DSTC7-AVSD.json``` is not included in official annotation file. For example, the following is the first sample from lbl file, it is:
```
{
        "type": "scene_aware_dialog",
        "version": "0.1",
        "dialogs": [
                {
                        "image_id": "VC5RZ",
                        "caption": "a man sits on a couch reading a book . he closes the book and puts it on a table . he grabs a pillow from next to him , cuddles it , and seems to fall asleep with it .",
                        "dialog": [
                                {
                                        "answer": "there is a man sitting on a couch .",
                                        "question": "are there any people in the video ?"
                                }
                        ],
...
```
However the related annotation from official has 6 references which are all different from the provided one in lbl file:
```
    "annotations": [
        {
            "image_id": 1,
            "id": 1,
            "caption": "there is man sitting on couch"
        },
        {
            "image_id": 1,
            "id": 2,
            "caption": "there is only one man in the video ."
        },
        {
            "image_id": 1,
            "id": 3,
            "caption": "there is a man sitting and couch"
        },
        {
            "image_id": 1,
            "id": 4,
            "caption": "there is one person , a man on a couch ."
        },
        {
            "image_id": 1,
            "id": 5,
            "caption": "there 's a guy sitting alone in his couch"
        },
        {
            "image_id": 1,
            "id": 6,
            "caption": "yes , there is one man sitting and reading on the couch ."
        },
```

**Comment by BigFishMaster** [comment]
I guess you use stop words ("i", "a", ",", "."). But the ```stopwords.txt``` file is missing under data/

**Comment by henryhungle** [comment]
> How to generate the following files under data/ folder? It is different from the officical files under `dstc7avsd_eval` folder(e.g., `test_set4DSTC7-AVSD_multiref.json`).
> 
> ```
> lbl_test_set4DSTC7-AVSD.json
> lbl_undiscloseonly_test_set4DSTC7-AVSD.json
> ```

At the time of writing the paper, only one reference response was provided instead of the complete 6 references. Therefore, the test script was run to evaluate based on this single reference only.

**Comment by henryhungle** [comment]
> I guess you use stop words ("i", "a", ",", "."). But the `stopwords.txt` file is missing under data/

The provided single reference responses are provided in data/lbl_test_set4DSTC7-AVSD.json. As I only want to evaluate on a specific dialogue turn in each test dialogue i.e. turn position with UNDISCLOSED as in the DSTC competition, the lbl_undiscloseonly_test_set4DSTC7-AVSD.json is used to compare with system generated responses and obtain metrics. No stopwords.txt was used.
