### ISSUE TITLE
I can't get the result reported in your paper

### ISSUE THREAD

**Issue by lizekang** [henryhungle/MTN#4]
I use the experiment settings in your paper and I use stopwords "." and ",". But I can't get the results reported in your paper. 
Here is my result:
Bleu_1: 0.351
Bleu_2: 0.236
Bleu_3: 0.167
Bleu_4: 0.122
METEOR: 0.162
ROUGE_L: 0.352
CIDEr: 1.194

Could you help me run the experiments and get the results reported in your paper? Thank you.

**Comment by henryhungle** [comment]
As the issue was closed, do let me know if you still encounter similar problems.
