### ISSUE TITLE
Could you evaluate your best result on the test set with multi reference ground truth?

### ISSUE THREAD

**Issue by lizekang** [henryhungle/MTN#5]

**Comment by henryhungle** [comment]
Currently a small version (d=512) of the model obtains the following scores with multi-reference gt: 
BLEU4: 0.392 
METEOR: 0.269 
ROUGE-L: 0.559 
CIDEr: 1.066

**Comment by lizekang** [comment]
Thanks for your reply. 
We used the small version (d=512) and got the following scores with single-reference gt which is similar to your paper.
BLEU4: 0.124
METEOR: 0.162
ROUGE-L: 0.352
CIDEr: 1.194
However, we got the following scores with multi-reference gt:
BLEU4: 0.331
METEOR: 0.271
ROUGE-L: 0.551
CIDEr: 1.019
We use the default settings described in your paper. And we use stop words ",", ".". We don't know what leads to this big gap in BLEU-4. Could you help me bring the gap?

**Comment by lizekang** [comment]
I wonder if our evaluation is correct. Could you send us your prediction results OR could you help us evaluate our prediction results?
Email: zekangli97@gmail.com
Thanks very much.

**Comment by henryhungle** [comment]
I dropped you an email @lizekang. I also used stop words "," and "."

**Comment by lizekang** [comment]
Thank you very much!

**Comment by ranpox** [comment]
Hi @lizekang, I have similar problems. Have you found out why?

**Comment by lizekang** [comment]
@ranpox I haven't found out...

**Comment by Leeyouxie** [comment]
Do you know the scores of 6 reference on paper? I did not find it.

**Comment by henryhungle** [comment]
The 6-reference ground truth was not available before the paper so the paper result was based on single-reference ground truth.
